jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - bash: |
      set -x
      sudo apt-get update
      sudo apt-get -y install \
         autoconf build-essential zlib1g-dev libjpeg-dev \
         docbook-xsl fop xsltproc libxml2-utils inkscape imagemagick
      ./autogen.sh
      ./configure --enable-werror --enable-doc-maintenance \
          --enable-show-failed-test-output
      make -j$(nproc) check
      make distfiles.zip
    displayName: 'Linux build and test'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/distfiles.zip'
      artifactName: distfiles
    displayName: 'Upload Artifacts'
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Artifacts'
    inputs:
      artifactName: distfiles
      downloadPath: $(System.DefaultWorkingDirectory)
  - bash: |
      unzip distfiles/distfiles.zip
      ls -l . doc
    displayName: 'Windows build and test'
  dependsOn: Linux
  condition: succeeded()
- job: macOS
  pool:
    vmImage: macOS-10.13
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Artifacts'
    inputs:
      artifactName: distfiles
      downloadPath: $(System.DefaultWorkingDirectory)
  - bash: |
      unzip distfiles/distfiles.zip
      ls -l . doc
    displayName: 'Mac build and test'
  dependsOn: Linux
  condition: succeeded()
